EOS-18028 Fixes collections issues in s3 execution (#167)
* Added --ignore=unittests in pytest.ini to ignore UT's from collections.

Signed-off-by: Vishal Dhobale <vishal.dhobale@seagate.com>

* Fix: AttributeError: 'MarkDecorator' object has no attribute 'alert'

Signed-off-by: Vishal Dhobale <vishal.dhobale@seagate.com>

* Added --ignore=tools in pytest.ini to ignore tool's from collections.

Signed-off-by: Vishal Dhobale <vishal.dhobale@seagate.com>

* Added missing markers in pytest.ini.

Signed-off-by: Vishal Dhobale <vishal.dhobale@seagate.com>

* Removed --capture=no only required in debugging.

Signed-off-by: Vishal Dhobale <vishal.dhobale@seagate.com>

Co-authored-by: Vikas Kumar Choudhary <66417432+VikasKumarC@users.noreply.github.com>