Hotfix object attribute (#555)
* Adding geventThread Lib

* Adding code to collect threads responses and unit testing

* incorporating review comments

* updated method signatures

* Incorporated review comments

* updated

Signed-off-by: VikasKumarC <vikas.kumar@seagate.com>

* updated as per requitements of codacy

* updated as per requitements of codacy

* updated for codacy requirements

Signed-off-by: VikasKumarC <vikas.kumar@seagate.com>

* for codacy requirements

* codacy requirements

* codacy requirements done

* Renamed const as datatypes and refactored dependencies

* Renamed const to datattypes and updated dependencies

* added module doc string

* S3 Tests Migration EOS-16320 EOS-16321 EOS-16326 EOS-16895 EOS-16900

* Incorporating review comments

* Capitazlised all constants

* Updated to incorporate review comments

* renamed test modules and updated as per suggestions

* moved cleanup logic to teardown

* updated to fix codacy issues

* review comments incorporated

* removed space from function decorators

* Updated for migration to pytest framework

* Updated assertion methods params

* Added Exception to remove TypeError: exceptions must derive from BaseException

Signed-off-by: VikasKumarC <vikas.kumar@seagate.com>

* Incorported review comments

* updated assernt wrappers

Signed-off-by: VikasKumarC <vikas.kumar@seagate.com>

* Migrating support bundle test

* Resolving codacy issues

* updated as per review comments

* HotFix:  ImportError: S3Helper is a singleton, use S3Helper.get_instance() to access existing object.

* Hotfix: OSError: [WinError 10051] A socket operation was attempted to an unreachable network

Signed-off-by: VikasKumarC <vikas.kumar@seagate.com>

* Ported aws_iam as per pytest framework requirements

* doc string updated

* Added cortxcli_test_lib

* Updated with endpoint changes and verified with run

* Updated with endpoint changes and verified with run

* Updated with endpoint changes and verified with run

* Updated with endpoint changes and verified with run

* Updated with endpoint changes and verified with run

* Updated with endpoint changes and verified with run

* fixed AttributeError: 'TestBucketLocation' object has no attribute 's3_obj'

Signed-off-by: Divya Kachhwaha <divya.kachhwaha@seagate.com>